# Generated by Django 5.2.4 on 2025-09-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0002_alter_candidate_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='q_id',
            new_name='qid',
        ),
    ]
